language: php

php:
  - 5.4
  - 5.5
  - 7.0

env:
  - LC_API_REGION=US LC_APP_ID=wnDg0lPt0wcYGJSiHRwHBhD4 LC_APP_KEY=u9ekx9HFSFFBErWwyWHFmPDy LC_APP_HOST=127.0.0.1 LC_APP_PORT=8081

script:
  - "make test_engine &"
  - phpunit --coverage-clover=coverage.xml test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks: https://hook.bearychat.com/=bw52Y/travis/6e26f4422b2871c20a5b2d40e1d49f73

