language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

env:
    - LEANCLOUD_API_SERVER="https://us.avoscloud.com" LEANCLOUD_APP_ID=wnDg0lPt0wcYGJSiHRwHBhD4 LEANCLOUD_APP_KEY=u9ekx9HFSFFBErWwyWHFmPDy LEANCLOUD_REGION=US LEANCLOUD_APP_HOST="127.0.0.1" LEANCLOUD_APP_PORT=8081 LEANCLOUD_WILDCARD_DOMAIN="lncldglobal.com"

install:
    - composer install

script:
    - "make test_engine &"
    - "php -r 'exit(PHP_VERSION_ID >= 70200 ? 0 : 1);' || vendor/bin/phpunit test/Php72ObjectDeprecated.php"
    - "./vendor/bin/phpunit --coverage-clover=coverage.xml test"

after_success:
    - bash <(curl -s https://codecov.io/bash)
